import { NextRequest, NextResponse } from 'next/server';
import OpenAI from 'openai';

const openai = new OpenAI({
  apiKey: process.env['OPENAI_API_KEY'],
});

export async function POST(request: NextRequest) {
  try {
    const { productType, color, style, brand } = await request.json();

    if (!productType || !color || !style) {
      return NextResponse.json({ 
        error: 'Missing required parameters: productType, color, style' 
      }, { status: 400 });
    }

    console.log(`🎨 Generating AI image for: ${brand} ${productType} (${color}, ${style})`);
    
    // Check if API key is valid
    const apiKey = process.env['OPENAI_API_KEY'];
    const isInvalidKey = !apiKey || 
                        apiKey.includes('sk-local') || 
                        apiKey.includes('your-api-key') || 
                        apiKey.includes('placeholder') ||
                        apiKey.length < 20 ||
                        !apiKey.startsWith('sk-');
    
    if (isInvalidKey) {
      console.log('Using fallback image due to invalid API key');
      return NextResponse.json({
        success: true,
        imageUrl: `https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=400&h=500&fit=crop&crop=center&auto=format&q=80`,
        productType,
        color,
        style,
        brand: brand || 'Fashion Brand',
        generatedBy: 'Fallback',
        timestamp: new Date().toISOString()
      });
    }

    // Create a detailed prompt for DALL-E
    const prompt = `Professional fashion photography of a ${color} ${style} ${productType} from ${brand || 'a fashion brand'}. 
    High-quality product shot on a clean white background, studio lighting, commercial fashion photography style. 
    The ${productType} should be ${style} style in ${color} color. 
    Clean, minimalist, professional e-commerce product image. 
    No text, no watermarks, no people, just the clothing item.`;

    console.log(`🤖 DALL-E prompt: ${prompt}`);

    const response = await openai.images.generate({
      model: "dall-e-3",
      prompt: prompt,
      n: 1,
      size: "1024x1024",
      quality: "standard",
      style: "natural"
    });

    const imageUrl = response.data?.[0]?.url;
    
    if (!imageUrl) {
      throw new Error('No image generated by DALL-E');
    }

    console.log(`✅ AI image generated successfully: ${imageUrl}`);

    return NextResponse.json({
      success: true,
      imageUrl: imageUrl,
      productType,
      color,
      style,
      brand: brand || 'Fashion Brand',
      generatedBy: 'DALL-E-3',
      timestamp: new Date().toISOString()
    });

  } catch (error) {
    console.error('AI image generation error:', error);
    
    // Fallback to placeholder image - use default values since body was already read
    return provideFallbackImage('tops', 'black', 'casual', 'ASOS');
  }
}

// Fallback function for when API key is invalid or generation fails
function provideFallbackImage(productType: string, color: string, style: string, brand?: string) {
  console.log('Providing fallback image...');
  
  // Generate a consistent seed based on product details
  const seed = `${productType}-${color}-${style}-${brand}`.split('').reduce((a, b) => {
    a = ((a << 5) - a + b.charCodeAt(0)) & 0xffffffff;
    return a;
  }, 0);
  
  // Use a reliable placeholder service with consistent images
  const fallbackUrl = `https://picsum.photos/seed/${seed}/400/500`;
  
  return NextResponse.json({
    success: true,
    imageUrl: fallbackUrl,
    productType,
    color,
    style,
    brand: brand || 'Fashion Brand',
    generatedBy: 'Fallback',
    timestamp: new Date().toISOString()
  });
}

export async function GET() {
  return NextResponse.json({
    name: 'AI Image Generation API',
    description: 'Generate realistic fashion product images using OpenAI DALL-E',
    version: '1.0.0',
    usage: {
      method: 'POST',
      endpoint: '/api/generate-image',
      body: {
        productType: 'string (required) - Type of clothing (tops, bottoms, dresses, etc.)',
        color: 'string (required) - Color of the item',
        style: 'string (required) - Style of the item',
        brand: 'string (optional) - Brand name'
      },
      response: {
        success: 'boolean',
        imageUrl: 'string - Generated image URL',
        generatedBy: 'string - DALL-E-3 or Fallback'
      }
    }
  });
}
